### ISSUE TITLE
could not rebase

### ISSUE THREAD

**Issue by stbischof** [martinpitt/ostree-pitti-workstation#1]
I followed the instructions in the README, but i could not rebase from silverblue 33
```
sudo ostree remote add --no-gpg-verify piware https://piware.de/ostree/pitti-workstation/
sudo rpm-ostree rebase piware:

```
i am new on ostree maybe beause of

```
sudo rpm-ostree rebase piware: 
Rebasing to piware:fedora/33/x86_64/silverblue
error: While pulling fedora/33/x86_64/silverblue: Server returned HTTP 404

ostree remote refs piware 
error: Remote refs not available; server has no summary file
```

ps:
would be nice to have `flatpack` support.

pps:
was surprised not to see `swaybg`

Und danke für die gute arbeit und ein frohes Fest

**Comment by martinpitt** [comment]
Oops! Sorry about that, of course it needs to specify the ref name: `rpm-ostree rebase piware:pitti-desktop`. I just tested that on a pristine Fedora CoreOS instance, which ought to behave like Silverblue in this regard.

I fixed the README and also my [blog post](https://piware.de/post/2020-12-13-ostree-sway/).

I don't use flatpack, and try to keep running services/processes at a minimum.

swaybg is already a dependency of sway, so it's installed. My sway config has

    output * bg /usr/share/backgrounds/default.png fill

which works just fine.

Danke, und schöne Feiertage!
