### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by Ramblurr** [martinpitt/ostree-pitti-workstation#3]
Hi there! I'm trying to build your tree from source. I'm on an updated  Fedora 35 Silverblue install, I check out your repo and execute `compose.sh` as root:

```
rpm-ostree version: 2021.12
No previous commit for pitti-desktop
Enabled rpm-md repositories: fedora-35-updates fedora-35-updates-testing fedora-35 rpmfusion-free rpmfusion-free-updates
Updating metadata for 'fedora-35-updates'... done
Updating metadata for 'fedora-35-updates-testing'... done
Updating metadata for 'fedora-35'... done
Updating metadata for 'rpmfusion-free'... done
Updating metadata for 'rpmfusion-free-updates'... done
Importing rpm-md... done
rpm-md repo 'fedora-35-updates'; generated: 2021-11-04T01:32:06Z solvables: 7556
rpm-md repo 'fedora-35-updates-testing'; generated: 2021-11-05T01:10:49Z solvables: 9208
rpm-md repo 'fedora-35'; generated: 2021-10-29T10:17:40Z solvables: 65732
rpm-md repo 'rpmfusion-free'; generated: 2021-10-23T21:56:55Z solvables: 521
rpm-md repo 'rpmfusion-free-updates'; generated: 2021-11-01T16:48:42Z solvables: 10
Resolving dependencies... done
Installing 977 packages:

..snip large list of packages..

Input state hash: ecf3ff575c3f95a4485894f4fa20ebfd7ea56008d21ec3bf102f686174c70545
Will download: 21 packages (42.0 MB)
Downloading from 'fedora-35'... done
Downloading from 'fedora-35-updates-testing'... done
Downloading from 'fedora-35-updates'... done
⠄ Importing packages  12/271 [░░░░░░░░░░░░░░░░░░░░] (7s) 
error: importing RPMs: package menu-cache-1.1.0-2.fc35.4.x86_64 cannot be verified and repo fedora-35 is GPG enabled: /proc/self/fd/15/cache/repomd/fedora-35-rpmostree-unset-releasever-x86_64/packages/menu-cache-1.1.0-2.fc35.4.x86_64.rpm could not be verified.
/proc/self/fd/15/cache/repomd/fedora-35-rpmostree-unset-releasever-x86_64/packages/menu-cache-1.1.0-2.fc35.4.x86_64.rpm
```
(menu-cache is a transitive dependency of pcmanfm)

I'm not sure if this is a bug in your setup exactly, but if I try to manually layer `menu-cache` with `rpm-ostree install` it works fine..

**Comment by martinpitt** [comment]
This script normally runs in a `fedora:latest` container (which is Fedora 34) in GitHub actions, where it still works fine.

My laptop is also Fedora 35 now, and I just ran `sudo ./compose.sh` successfully. You may have hit a bad mirror, or some networking flake or so? Can you try again? Either way, I don't see how the yaml could influence the signatures of packages, that happens lower in the stack (between rpm-ostree, dnf, and rpm).

For comparison, you could also try to build fedora-lxqt.yaml or so instead of pitti-desktop.yaml.

**Comment by Ramblurr** [comment]
I just cloned the [upstream workstation-ostree-config](https://pagure.io/workstation-ostree-config) and tried to build fedora-lxqt.yaml, and hit the exact same error on the same menu-cache package.

I'll try again in an isolated container, and if I continue having problems take my questions to the fedora forums or bug tracker. 

Sorry for the noise!

I'm very keen on trying out this silverblue "variant", I didn't realize it was so easy to create your own ostree bases.
