### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by claudiusraphael** [martinpitt/ostree-pitti-workstation#4]
Added repo, rebased to it from Fedora Silverblue 35 and Kinoite 35. After reboot ended up in tty for login, but my user credentials aren't accepted.

Any idea?

**Comment by martinpitt** [comment]
Not off-hand. I use systemd-homed for my real user accounts, and PAM config is patched accordingly. However, I also have a "standard" local user account, and that works fine. Do you perhaps use any non-default configuration, like 2FA, LDAP, kerberos, IdM, etc? I suggest to boot with `systemd.debug-shell` (see `man systemd-debug-generator`), go to the debug VT (Ctrl+Alt+F9), start `journalctl -f`, try to log in on VT1 and check the particular error message.

**Comment by claudiusraphael** [comment]
Hmm, nah was just a regular install of Fedora Silverblue 35 with a standard user-account. I first thought i might have tried it initially in a linux-container and due to my setup on that Proxmox VE the user account might have been passed through (PAM) but that wasn't the case, i installed it bare-metal (just on that same machine) on a separate free space, double checked. I come back to this, when i try a fresh install on another machine.

Care to share your exact setup as a reference?

**Comment by martinpitt** [comment]
> Care to share your exact setup as a reference?

That's the thing with OSTree -- this *is* my exact setup :grinning: It includes the necessary PAM changes for systemd-homed.

The only things in `sudo diff -Nur /usr/etc/ /etc/` are unrelated to logging in -- cockpit certificate, /etc/fstab, my fallback standard user account, and NetworkManager connections.

**Comment by busla** [comment]
I also ended up in login tty, but after login and reboot, I ended up in Sway 😅
