### ISSUE TITLE
question: iwd commented out

### ISSUE THREAD

**Issue by busla** [martinpitt/ostree-pitti-workstation#5]
Hey, thanks for sharing all of this! It's been a great learning resource for me on how to structure a custom ostree build 🙏

Just out of curiosity, did you have issues with `iwd`, since its commented out?

https://github.com/martinpitt/ostree-pitti-workstation/blob/pitti-desktop-f36/pitti-post.sh#L16

**Comment by martinpitt** [comment]
See commit c68303793ad1ddca87128b26f1bb644ae08ff094 , and my report in https://bugzilla.redhat.com/show_bug.cgi?id=1915641 . I haven't tried it since then.
