### ISSUE TITLE
sway config location

### ISSUE THREAD

**Issue by gigatexal** [martinpitt/ostree-pitti-workstation#7]
I love this project -- until there's a first-party way to get sway with silverblue (maybe a spin or something from the fedora folks themselves) I will use this as my daily. 

I am currently trying it out in a vm before I nuke and pave my main workstation to run silverblue + your workstation repo as a rebase.

I am looking for where the default or the current sway.conf file happens to be as I can't seem to find it in any of the normal locations.

**Comment by martinpitt** [comment]
There is no specific config of sway. The Fedora package does not ship a default config, just an empty /etc/sway/config.d. It's best to keep your sway config in your home dir, i.e. ~/.config/sway/ (mine is [here](https://piware.de/tools/sway-config.tar))

**Comment by gigatexal** [comment]
Thank you!
