### ISSUE TITLE
Broken rpmfusion repo when running rpm-ostree install

### ISSUE THREAD

**Issue by gigatexal** [martinpitt/ostree-pitti-workstation#8]
![image](https://user-images.githubusercontent.com/605357/228031265-ab8b39f7-241c-4759-9937-acf4334be9d4.png)

The nvidia repo seems to be broken for want of working gpg keys -- this is on a new/fresh rebase of a clean silverblue install with your setup.

**Comment by gigatexal** [comment]
might be worth checking the rpmfusion repo too I guess

**Comment by martinpitt** [comment]
The rpmfusion repo is even more broken -- The OSTree [does not even build](https://github.com/martinpitt/ostree-pitti-workstation/actions/runs/4517005572/jobs/7955870773), as ffmpeg is uninstallable. That's why I [disabled it for now](https://github.com/martinpitt/ostree-pitti-workstation/commit/0c8c5271c60e39ce02c4e3e35c4162397bef5d70). But there's nothing that I can do about it on my side, please report this to rpmfusion. Thanks!

**Comment by gigatexal** [comment]
@martinpitt not sure if you will find this helpful but I guess the error in the build is intentional(!) and there's a suggested workaround that's not ideal: https://bugzilla.rpmfusion.org/show_bug.cgi?id=6617

**Comment by martinpitt** [comment]
Thanks for the link @gigatexal : These recipes don't directly apply to this custom OSTree, but I did put back at least the "free" variants of libav. That should help a bit for video playback. Either way, installing alacritty etc. should work again, as the rpmfusion repo is gone.

**Comment by gigatexal** [comment]
@martinpitt apologies for the thread necro ... with rpmfusion gone (since I am using this in a VM for testing but plan to use it on a workstation that has a nvidia gpu) is one still able to run/install nvidia gpu drivers?

**Comment by gigatexal** [comment]
![image](https://user-images.githubusercontent.com/605357/229287281-29898b2a-e21e-4a2b-bf43-b64a442364c5.png)
rpmfusion continues to be problematic :(

**Comment by martinpitt** [comment]
@gigatexal I'm afraid I know nothing about the nvidia drivers. Of course, feel free to add back the repo to your image build (or do it live as an overlay). I still want to find a solution for the video codecs at some point, too many youtube videos have an unbearable performance now.

**Comment by gigatexal** [comment]
I'll investigate this, gotta find a disk to run silverblue on my main workstation as it's the only one with a nvidia gpu. 

ok, i'll stop necro'ing this thread.
